# Generated by Django 2.0.2 on 2018-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instituicao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('YL', 'Young ling'), ('PW', 'Padawan'), ('JD', 'Jedi'), ('MJ', 'Mestre Jedi')], default='YL', max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('lattes', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('atividade', models.ManyToManyField(to='produtos.Atividade')),
                ('curso', models.ManyToManyField(to='pessoas.Curso')),
                ('formacao', models.ManyToManyField(to='pessoas.Formacao')),
                ('projeto', models.ManyToManyField(to='produtos.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jedi',
            name='social',
            field=models.ManyToManyField(to='pessoas.Social'),
        ),
    ]
