# Generated by Django 2.0.2 on 2018-03-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instituicao', models.CharField(max_length=255)),
                ('finalizado', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('YL', 'Young ling'), ('PW', 'Padawan'), ('JD', 'Jedi'), ('MJ', 'Mestre Jedi')], default='YL', max_length=2)),
                ('papel', models.CharField(choices=[('ES', 'Estudante'), ('PR', 'Professor'), ('TE', 'Tecnico'), ('OU', 'Outro')], default='OU', max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('lattes', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(null=True)),
                ('atividade', models.ManyToManyField(to='produtos.Atividade')),
                ('formacao', models.ManyToManyField(to='pessoas.Formacao')),
                ('projeto', models.ManyToManyField(to='projetos.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Membro')),
            ],
        ),
        migrations.AddField(
            model_name='bolsa',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Membro'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto'),
        ),
    ]
