language: python
python:
- '3.5'

branches:
  only:
  - master
  - desenvolvimento

install:
  - pip install -r requirements.txt

script:
  - cd millennium_falcon
  - python manage.py behave

notifications:
  slack: leds:WcbvqiRBqLkfvG5n8ElKt4Id