language: python
dist: trusty
sudo: false
python:
  - '3.5'
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "leds-github"
    token:
      secure: "a73148b8d8c91914c96acfe7e091f08e4f74b68f"

branches:
  only:
  - master
  - desenvolvimento

install:
  - pip install -r requirements.txt

script:
  - cd millennium_falcon
  - python manage.py behave
  - cd ..
  - sonar-scanner

notifications:
  slack: leds:WcbvqiRBqLkfvG5n8ElKt4Id
