dist: trusty
sudo: false
language: python
python:
- '3.5'
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: icarodgl-github
    token:
      secure: "$SONAR_TOKEN"
branches:
  only:
  - master
  - Desenvolvimento
install:
- pip install -r requirements.txt
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: adCgDe9whowjZ+A39ctmtrJjx5kI9O59z+JOV7ksh7fW8Nkowe+eHKfcfSqk0CYb5umfDfr9gkSR7IrIxVGvbpDn2p65qrpa9I3CblrOBeG64GmPbGLZapPJxFPg9tbjGFruew4B4UE3mQjx5HyTJO0aJc/1ZTwxL5t6jg1oBs42mOINusuuYnqqQ/J3W8UunHEUWA+glUKjt4mAEQbOI7B8X09a1saZqyFYdVg91X7e786XnHjCkvYZAiDJXCmq1vTijgkPSyboi+OwZPW8+Mo051ke1jHeWxSrXrK5jBBNsKa5ohpAGBbR7EwGvYB7lEuDyAOqtP8pvAJPCSPZzHP1V/x+iSiyC5AUUmfMoQ9xnATtgg4gw2IS+lYJAJ0+rFHjYdiae1UzwwO+IblemYRkdolpkYMD4tBxXcuHE6mMhRyNeY2Ot3QIo6ZU3BGyBlrUEu1AswPdqQxhlEVl7Bg17dEtM/cGVU+BAwSkckitsZB7wV9Y5DZXYpd/si8wrVznEdmqwr58dfWPhjEC1rX37zigIPdGA+8c/oqgCYgGNuVo7NLGOvtn9brJD+PtCdgZaPkpCjBwfHuRNnwpQN/YdC6sOPFjjyDzP4SQLfwQpYvG8CvY4U2iCEsVodJKGfVYYrub+SU8g1cP7UA8pbkf+KFbjpXTY4O9/4zpzOA=
  app: millennium-falcon
  on:
    repo: icarodgl/millennium-falcon
