dist: trusty
sudo: false
language: python
python:
- '3.5'
jdk:
- oraclejdk8
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: heroku_key
    app: millenium-falcon
  on:
    repo: icarodgl/millennium-falcon
