language: python
dist: trusty
sudo: false
python:
  - '3.5'
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "leds-github"
    token:
      secure: "$SONAR_TOKEN"

branches:
  only:
  - master
  - desenvolvimento

install:
  - pip install -r requirements.txt

script:
  - cd millenium_falcon
  - python manage.py behave
  - cd ..
  - sonar-scanner

notifications:
  slack: $SLACK_TOKEN
