# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0008_auto_20170517_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('papel', models.CharField(max_length=255)),
                ('entrada_leds', models.DateField()),
                ('saida_leds', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('telefone', models.CharField(max_length=255, null=True)),
                ('cpf', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa_academica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa')),
                ('lattes', models.URLField(max_length=255, null=True)),
            ],
            bases=('pessoas.pessoa',),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa')),
                ('setor_vinculado', models.CharField(max_length=255, null=True)),
            ],
            bases=('pessoas.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Bolsa'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_academica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa_academica')),
                ('periodo_atual', models.IntegerField()),
                ('periodo_saida', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(null=True)),
            ],
            bases=('pessoas.pessoa_academica',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_academica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa_academica')),
                ('setor_vinculado', models.CharField(max_length=255, null=True)),
                ('siape', models.CharField(max_length=255, null=True)),
            ],
            bases=('pessoas.pessoa_academica',),
        ),
        migrations.AddField(
            model_name='pessoa_academica',
            name='habilidades',
            field=models.ManyToManyField(to='pessoas.Habilidade'),
        ),
    ]
