# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_academica_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_academica',
            name='habilidades',
            field=models.ManyToManyField(related_name='habilidaeds_pessoais', to='pessoas.Habilidade'),
        ),
    ]
