# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_auto_20170517_1827'),
        ('pessoas', '0006_remove_pessoa_bolsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Bolsa'),
        ),
        migrations.AddField(
            model_name='pessoa_academica',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, to='pessoas.Habilidade'),
        ),
    ]
