# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_remove_pessoa_academica_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa_academica',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='pessoa_academica_ptr',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='pessoa_academica_ptr',
        ),
        migrations.AddField(
            model_name='aluno',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='habilidades',
            field=models.ManyToManyField(to='pessoas.Habilidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='lattes',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pessoa_academica',
        ),
    ]
