# Generated by Django 2.0.2 on 2018-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('TC', 'TCC'), ('PA', 'Palestra'), ('MC', 'Mini Curso'), ('OU', 'Outro')], max_length=2)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=255, null=True)),
                ('Descricao', models.TextField(null=True)),
            ],
        ),
    ]
