# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceiro', models.CharField(max_length=255)),
                ('nome_representante', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='representante_parceiro',
            name='pessoa_ptr',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='projeto_envolvido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Projeto'),
        ),
        migrations.AddField(
            model_name='professor',
            name='setor_vinculado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor_vinculado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Representante_parceiro',
        ),
        migrations.AddField(
            model_name='projeto',
            name='parceiro_envolvido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Parceiro'),
        ),
    ]
