# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20170512_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao_bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(null=True)),
                ('fim', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bolsa', models.CharField(blank=True, max_length=255)),
                ('valor_bolsa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fomento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='periodo',
            new_name='periodo_atual',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='status_bolsa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='valor_bolsa',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='fomento',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='email',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='lattes',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodo_saida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='cnpj',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pessoas_envolvidas',
            field=models.ManyToManyField(to='gestao.Pessoa'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='projeto_envolvido',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='projeto_envolvido',
            field=models.ManyToManyField(to='gestao.Projeto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='saida_leds',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fomento',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Parceiro'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='fomento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Fomento'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.Projeto'),
        ),
        migrations.AddField(
            model_name='alocacao_bolsa',
            name='bolsa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Bolsa'),
        ),
        migrations.AddField(
            model_name='alocacao_bolsa',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Pessoa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='habilidades',
            field=models.ManyToManyField(to='gestao.Habilidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='bolsa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Bolsa'),
        ),
    ]
