# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20170516_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='professor',
            name='habilidades',
            field=models.ManyToManyField(to='gestao.Habilidade'),
        ),
        migrations.AddField(
            model_name='professor',
            name='lattes',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='siape',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
