# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_auto_20170516_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('telefone', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Bolsa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pessoas_envolvidas',
            field=models.ManyToManyField(blank=True, null=True, to='gestao.Pessoa'),
        ),
        migrations.AddField(
            model_name='representante',
            name='projeto_envolvido',
            field=models.ManyToManyField(to='gestao.Projeto'),
        ),
    ]
