# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_auto_20170516_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='representante_do_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Representante'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='nome_representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Representante'),
        ),
    ]
