# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_auto_20170516_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacao_bolsa',
            name='bolsa',
        ),
        migrations.RemoveField(
            model_name='alocacao_bolsa',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='bolsa',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='projeto_envolvido',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='bolsa',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='representante_do_projeto',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='projeto_envolvido',
        ),
        migrations.AddField(
            model_name='representante',
            name='funcao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pessoas_envolvidas',
            field=models.ManyToManyField(blank=True, to='pessoas.Pessoa'),
        ),
        migrations.DeleteModel(
            name='Alocacao_bolsa',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Habilidade',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
