# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_projeto_pessoas_envolvidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='pessoas_envolvidas',
            field=models.ManyToManyField(blank=True, related_name='pessoas_do_projeto', to='pessoas.Pessoa'),
        ),
    ]
