# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_remove_projeto_pessoas_envolvidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa',
            name='fomento',
        ),
        migrations.RemoveField(
            model_name='fomento',
            name='parceiro',
        ),
        migrations.RemoveField(
            model_name='parceiro',
            name='nome_representante',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='parceiro_envolvido',
        ),
    ]
