# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_auto_20170517_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bolsa',
        ),
        migrations.DeleteModel(
            name='Fomento',
        ),
        migrations.DeleteModel(
            name='Parceiro',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
