# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_remove_pessoa_bolsa'),
        ('gestao', '0015_bolsa_fomento_parceiro_projeto_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='fomento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Fomento'),
        ),
        migrations.AddField(
            model_name='fomento',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Parceiro'),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='nome_representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Representante'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='parceiro_envolvido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Parceiro'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pessoas_envolvidas',
            field=models.ManyToManyField(blank=True, related_name='pessoas_do_projeto', to='pessoas.Pessoa'),
        ),
    ]
